
import Head from 'next/head'
import Hero from './components/Hero'
import Main  from './components/Main'
import {useState} from 'react'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {FaRebel} from 'react-icons/fa'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Padilha Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons8-sigma-50.png" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-[#000501]'>
        <nav className='py-7 mb-12 flex justify-between dark:bg-[#000501]'>
            <h1 className='text-xl font-burtons dark:text-white'>Developed by Padilha</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl dark:text-white' 
              onClick={()=> setDarkMode(!darkMode)}
              /></li>
              <li>
                <a href="/CV PadilhaFrontend.pdf" download
                className='bg-gradient-to-tr from-red-800 to-purple-800 text-white font-semibold px-4 py-2 rounded-md ml-8'>
                  Resume
                </a>
              </li>
            </ul>
        </nav>
        <Hero/>
        <Main/>
      </main>
      
    </div>
  )
}
